### ISSUE TITLE
预置模型库读取TFRecord数据集很慢

### ISSUE THREAD

**Issue by Charliechow** [huaweicloud/dls-example#10]
### 基本信息

- Python版本: 2.7
- MoXing版本：
- 浏览器：

### 问题描述 / 重现步骤

运行作业日志提示如下信息，并经过很长时间都没有反应。日志一直卡在下面这句话。

```
INFO:tensorflow:Find tfrecord files. Using tfrecord files in this job.
INFO:tensorflow:Automatically extracting num_samples from tfrecord. If the dataset is large, it may take some time. You can also manually specify the num_samples to Dataset to save time.
```

#### 作业基本信息

- 相关作业类型: 预置模型库-创建训练作业
- 作业ID:
- 引擎类型: TensorFlow
- 运行参数：

- 计算节点个数：
- 计算节点规格：

**Comment by sleepfin** [comment]
这个现象的原因是用户使用的tfrecord文件作为数据集，MoXing在扫描tfrecord文件并抽取总样本数量的值，如果tfrecord文件所在位置是一个网络文件系统，而该文件系统的IO速度不高，很可能在这一步会停留很久。

解决办法：根据用户数据集的实际情况填写tfrecord文件的总样本数量。

可能涉及的API：

1) mox.get_tfrecord

```
mox.get_tfrecord(..., num_samples=1000, ...)
```

2) 所有BaseTFRecordMetadata类以及其子类：

```
BaseTFRecordMetadata(..., num_samples=1000, ...)
```

3) DLS服务中的预置模型库：

当使用的是未划分的单数据集时，即train或eval数据集，手动指定运行参数： `samples_per_epoch`，表示所选数据集中的总样本数量。

当使用的是划分好的数据集时，即train和eval数据集，手动指定运行参数：` samples_per_epoch`和`samples_per_epoch_eval`，分别表示所选train数据集和eval数据集中的总样本数量。
