### ISSUE TITLE
启动预测作业找不到模型, no versions of servable mode found

### ISSUE THREAD

**Issue by Charliechow** [huaweicloud/dls-example#11]
### 基本信息

- Python版本: 2.7
- MoXing版本：
- 浏览器：

### 问题描述 / 重现步骤

启动预测作业，如果提示信息类似如下：

```
tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:268] No versions of servable resnet_v1_50 found under base path s3://dls-test/log/resnet_v1_50/1/
```

#### 作业基本信息

- 相关作业类型: 预测作业
- 作业ID:
- 引擎类型: TensorFlow
- 运行参数：

- 计算节点个数：
- 计算节点规格：

**Comment by sleepfin** [comment]
说明没有找到可以用于TF-Serving的模型文件。导出的模型应有如下目录结构

```
|- log_dir
    |- 1
        |- svaed_model.pb
        |- variables
            |- variables.data-00000-of-00001
            |- variables.index
```

其中1表示模型的版本号，启动预测服务需要指定到目录log_dir这层，在这个案例中就是s3://dls-test/log/resnet_v1_50而不是s3://dls-test/log/resnet_v1_50/1/


当导出模型的目录下有多个版本号的模型时，如1，2，99，TF-Serving会自动选取数字最大99的模型做预测，当一个作业往该目录下继续输出了模型100，TF-Serving预测服务不需要重启，自动切换到100的模型上。在MoXing中，mox.ExportSpec(..., version=x, ...)，version参数就是用来指定该版本号，缺省值为-1，表示自动自增，即在输出目录下找到最大的版本号并+1，然后保存。
