### ISSUE TITLE
训练作业没有训练信息，很快就结束训练了

### ISSUE THREAD

**Issue by Charliechow** [huaweicloud/dls-example#12]
### 基本信息

- Python版本: 2.7
- MoXing版本：
- 浏览器：

### 问题描述 / 重现步骤

启动一个训练作业时，发现很快就结束了，控制台也没有打印任何与loss或是accuracy相关的信息。

输出日志信息如下：

```
INFO:tensorflow:Restoring parameters from s3://bucket_name/log/model.ckpt-xxx
INFO:tensorflow:Saving checkpoints for xxx into s3://bucket_name/log
```

#### 作业基本信息

- 相关作业类型: 训练作业
- 作业ID:
- 引擎类型: TensorFlow
- 运行参数：

- 计算节点个数：
- 计算节点规格：

**Comment by sleepfin** [comment]
这是因为训练开始时，在用户指定的输出日志路径（train_url或是log_dir）中已经存在了checkpoint，例如一个训练到1000步的checkpoint文件：model.ckpt-1000，而用户启动的训练作业指定的训练步数也是1000步，此时就会认为不需要再训练，就直接退出了。

如果想在原有checkpoint基础上继续训练，可以将训练步数指定到更大的步数。如果想重新训练，可以将原来的checkpoint文件删除或者指定一个全新的输出日志路径。
