### ISSUE TITLE
创建训练作业失败

### ISSUE THREAD

**Issue by raygenyang** [huaweicloud/dls-example#13]
### 基本信息

- Python版本: 2.7
- MoXing版本：(未使用则不填写)
- 浏览器：

### 问题描述 / 重现步骤

这是训练集数据

![image](https://user-images.githubusercontent.com/29909338/39222130-9438c960-486d-11e8-91bb-23d30aa390c8.png)

#### 作业基本信息

- 相关作业类型: 训练作业
- 作业ID:
- 引擎类型: TensorFlow
- 运行参数：train_url=s3://donotdel-dls/models/
model_name=resnet_v1_50
checkpoint_url=s3://donotdel-dls/models/resnet_v1_50/
batch_size=2

- 计算节点个数：1
- 计算节点规格：8核 | 32GiB
--

#### 相关源码 / 输出日志
```
INFO:tensorflow:Total 3301 files found in s3://donotdel-dls-test/models/data/
INFO:tensorflow:Total number of samples is 3301
INFO:tensorflow:Labels index to name:
INFO:tensorflow:0: daisy
INFO:tensorflow:1: dandelion
INFO:tensorflow:2: roses
INFO:tensorflow:3: sunflowers
INFO:tensorflow:4: tulips
Traceback (most recent call last):
  File "resnet_v1_50_code/finetune_model.py", line 501, in <module>
    main()
  File "resnet_v1_50_code/finetune_model.py", line 262, in main
    raise ValueError("learning_rate_strategy should be like: 'e_0:l_0,e_1:l_1,...,e_n:l_n. "
ValueError: learning_rate_strategy should be like: 'e_0:l_0,e_1:l_1,...,e_n:l_n. e_i:l_i represents that from epoch e_i-1 to e_i use learning rate l_i. And training will stop at epoch e_n'

```

**Comment by gclouding** [comment]
从预置模型库创建训练作业，如果选择的是TensorFlow的图像分类模型，默认的运行参数只有
- train_url
- checkpoint_path
- model_name
当选择的`数据集路径`中同时包含了`训练集`和`验证集`的时候，训练作业的学习率策略会被自动配置（根据验证集上的正确率自动调整），此时数据集路径应为如下结构：
```
data_url
  |- train
    |- label_0
      |- xxx.jpg
      ...
    |- label_1
      |- xxx.jpg
      ...
    ...
  |- eval
    |- label_0
      |- xxx.jpg
      ...
    |- label_1
      |- xxx.jpg
      ...
    ...
```

如果用户仅选择了单一的数据集（即训练集），即如下结构：
```
data_url
  |- label_0
    |- xxx.jpg
    ...
  |- label_1
    |- xxx.jpg
    ...
  ...
```
则需要用户配置学习率。配置方法为增加运行参数
learning_rate_strategy=10:0.01,20:0.001
含义是：0\~10个epoch使用0.01为学习率，10\~20个epoch使用0.001为学习率，一共训练20个epoch
用户可以根据实际情况调整学习率策略
