### ISSUE TITLE
预测客户端，no module named predict_pb2

### ISSUE THREAD

**Issue by hbpaul** [huaweicloud/dls-example#14]
在命令行中输入示例，如下，
python dls-tfserving-client/python/predict.py \
--task_type="image_classification" \
--host=my.host \
--port=my.port \
--data_path="xx/dls-tfserving-client/data/flowers/flower1.jpg" \
--labels_file_path="xx/dls-tfserving-client/data/flowers/labels.txt" \
--model_name="graph"
出现如下问题，请问如何解决呢
![image](https://user-images.githubusercontent.com/20982458/39735338-bd2f6b5e-52ad-11e8-9312-ee73105495dc.png)

**Comment by sleepfin** [comment]
可能是因为没有设置PYTHONPATH引起的
假设你的客户端工程目录是在：

    /xx/xx/dls-tfserving-client/

则运行的脚本应该是：

    /xx/xx/dls-tfserving-client/python/predict.py

尝试在执行脚本之前添加PYTHONPATH:

    export PYTHONPATH=/xx/xx/dls-tfserving-client/python:$PYTHONPATH

然后在启动脚本：

    python /xx/xx/dls-tfserving-client/python/predict.py --xxx=xxx...
