### ISSUE TITLE
无法打开上传的juypter notebook 也无法引用同目录下的.py 文件

### ISSUE THREAD

**Issue by zcwei** [huaweicloud/dls-example#24]
### 基本信息

- Python版本: 3.6
- MoXing版本：(未使用则不填写)
- 浏览器：chrome

### 问题描述 / 重现步骤
1. 无法打开我上传的文件，文件路径：bucket-8579 ＞zhicheng-> keyword_extraction.ipynb. 打开以后提示说：string do not have split method之类的
2. 试图引用 import Ipynb_importer ，但是报错说找不到文件，但是文件就在工作目录下啊
(简单描述问题信息，如果是bug，请描述重现步骤)

#### 作业基本信息

- 相关作业类型: 
- 作业ID:
- 引擎类型: TensorFlow 
- 运行参数：

- 计算节点个数：
- 计算节点规格：

#### 相关源码 / 输出日志
```
(Your Log Here)
```

**Comment by sleepfin** [comment]
关于问题2，假设你的notebook是这样的：
```
a.py
b.py
```
如果你要在a中import b，那么现在notebook中勾选b.py文件，然后点击上方`SYNC TO PYTHONPATH`按钮，然后就可以在a.py中使用如下代码
```
import b
```

**Comment by chkPocket** [comment]
关于问题一：
应该是由ipynb版本不一致，造成notebook导入不兼容。  
可以通过`conda -V`命令在导出ipynb环境中确认版本；  
DLS目前的conda版本为`4.3.0`;
