### ISSUE TITLE
开发环境中无法新建python

### ISSUE THREAD

**Issue by huazhenseu** [huaweicloud/dls-example#27]
### 基本信息

- Python版本: (2.7 / 3.6)
- MoXing版本：(未使用则不填写)
- 浏览器：

### 问题描述 / 重现步骤
开发环境中新建python 提示：Unexpected error while saving file : Untitled.ipynb unable to open database file

(简单描述问题信息，如果是bug，请描述重现步骤)

已经解决，原因是由于用户调试过程中，自己的代码出错生产了这些core dump，导致磁盘空间不足。用户再调试的时候，可以删除掉/home/work目录下面产生的core dump，这样就不会有问题

**Comment by coldsheephot** [comment]
已经解决，原因是由于用户调试过程中，自己的代码出错生产了这些core dump，导致磁盘空间不足。用户再调试的时候，可以删除掉/home/work目录下面产生的core dump，这样就不会有问题
