### ISSUE TITLE
训练作业日志显示错误信息：  AttributeError: 'module' object has no attribute '_FlagValues'

### ISSUE THREAD

**Issue by Charliechow** [huaweicloud/dls-example#6]
训练作业日志显示错误信息：  AttributeError: 'module' object has no attribute '_FlagValues'

**Comment by sleepfin** [comment]
很有可能就是在使用MoXing-TensorFlow-1.4的情况下TensorFlow的版本不是1.4的，通过以下命令查看TensorFlow版本
‘’‘
pip list | grep tensorflow
’‘’

或者在python中输入
‘’‘
import tensorflow as tf
tf.__version__
’‘’
