### ISSUE TITLE
训练作业日志错误信息： error: unrecognized arguments: --data_url=s3://my_bucket/data

### ISSUE THREAD

**Issue by Charliechow** [huaweicloud/dls-example#7]
训练作业日志错误日志： error: unrecognized arguments: --data_url=s3://my_bucket/data

**Comment by sleepfin** [comment]
你在自己的训练脚本中应该试试用了argparse来定义运行参数。

在外部命令行给入的参数（或者在DLS服务中输入的运行参数）如果在脚本中没有被argparse定义过，则会出现这个错误

解决办法，用以下方法：

    args, unparsed = parser.parse_known_args()

代替

    args = parser.parse_args()

**Comment by sleepfin** [comment]
DLS会给用户脚本额外传递一些参数，如num_gpus, data_url等，如果用户脚本不允许解析未定义的参数，则会报错。

如果你使用的是TensorFlow高版本（如tf-1.8），命令行参数使用absl包定义，如下的写法是不允许传入未定义的参数的：

```
import tensorflow as tf
tf.flags.DEFINE_xxx
...
flags = tf.flags.FLAGS

def main():
  print(flags.xxx)


if __name__ == '__main__':
  main()
```

需要修改为：

```
import tensorflow as tf
tf.flags.DEFINE_xxx
...
flags = tf.flags.FLAGS

def main(*args):
  print(flags.xxx)


if __name__ == '__main__':
  tf.app.run(main=main)
```

**Comment by ForeverPs** [comment]
![image](https://user-images.githubusercontent.com/47919727/62019291-ceb8dd80-b1f0-11e9-82d7-6f602a9a96e0.png)
![image](https://user-images.githubusercontent.com/47919727/62019317-ebedac00-b1f0-11e9-9b3e-dd4870e250a2.png)
我这样写的依然报错，求助
