### ISSUE TITLE
训练作业失败，ImportError: No module named module_dir

### ISSUE THREAD

**Issue by Charliechow** [huaweicloud/dls-example#9]
### 基本信息

- Python版本: 2.7
- MoXing版本：
- 浏览器：

### 问题描述 / 重现步骤

代码结构如下：

```
project_dir
    |- main.py
  |- module_dir
    |- module_file.py
```

用户在main.py中有代码

```
from module_dir import module_file
```

发生如下错误：

```
Traceback (most recent call last):
  File "project_dir/main.py", line 1, in <module>
    from module_dir import module_file
ImportError: No module named module_dir
```

#### 作业基本信息

- 相关作业类型: 训练作业
- 作业ID:
- 引擎类型: TensorFlow
- 运行参数：

- 计算节点个数：
- 计算节点规格：

**Comment by sleepfin** [comment]
这份代码如果在本地运行，需要将project_dir加入到PYTHONPATH或者将整个project_dir安装到site-package中才能运行，但是在DLS中没有办法进行这些操作，所以可以将project_dir加入到sys.path中解决该问题，步骤如下：

首先保证被import的module中有__init__.py存在，创建module_dir的__init__.py，代码结构如下：

```
project_dir
  |- main.py
  |- module_dir
    |- __init__.py
    |- module_file.py
```

在main.py中将project_dir添加到sys.path中，由于用户不知道project_dir在容器中的位置，所以利用相对路径：

```
import os
import sys
# __file__为获取当前执行脚本main.py的绝对路径
# os.path.dirname(__file__)获取main.py的父目录，即project_dir的绝对路径
current_path = os.path.dirname(__file__)
sys.path.append(current_path)
# 在sys.path.append执行完毕之后再导入其他模块
from module_dir import module_file
```

再次提交作业运行即可。
